# This is a basic workflow to help you get started with Actions

name: Mdbook Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      uses: actions-rs/install@v0.1
      with:
        crate: mdbook
        version: latest
        use-tool-cache: true
    - name: Build mdbook
      run: mdbook build
    - name: Cache artifact
      uses: actions/upload-artifact@v1
      with:
        name: book
        path: ./book

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: book
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 这里需要在项目配置
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./book
          publish_branch: master
          allow_empty_commit: true
          user_name: "draw233"
          user_email: "1165644829@qq.com"
          force_orphan: true

